start:
	docker-compose -f artifacts/docker-compose.yaml up

start-ca:
	docker-compose -f artifacts/ca.yaml up

pull-binaries:
	chmod +x ./artifacts/pull-binaries.sh
	./artifacts/pull-binaries.sh 1.0.2