#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  fabric-ca:

services:
  rca-org0:
    container_name: rca-org0
    image: hyperledger/fabric-ca
    command: /bin/bash -c '/scripts/start-root-ca.sh 2>&1 | tee /data/logs/rca-org0.log'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org0
      - FABRIC_CA_SERVER_CSR_HOSTS=rca-org0
      - FABRIC_CA_SERVER_DEBUG=true
      - BOOTSTRAP_USER_PASS=rca-org0-admin:rca-org0-adminpw
      - TARGET_CERTFILE=/data/org0-ca-cert.pem
    ports:
      - 7054:7054
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks:
      - fabric-ca

  rca-org1:
    container_name: rca-org1
    image: hyperledger/fabric-ca
    command: /bin/bash -c '/scripts/start-root-ca.sh 2>&1 | tee /data/logs/rca-org1.log'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org1-admin
      - FABRIC_CA_SERVER_CSR_HOSTS=rca-org1-admin
      - FABRIC_CA_SERVER_DEBUG=true
      - BOOTSTRAP_USER_PASS=rca-org1-admin:rca-org1-adminpw
      - TARGET_CERTFILE=/data/org1-ca-cert.pem
    ports:
      - 8054:7054
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks:
      - fabric-ca

  rca-org2:
    container_name: rca-org2
    image: hyperledger/fabric-ca
    command: /bin/bash -c '/scripts/start-root-ca.sh 2>&1 | tee /data/logs/rca-org2.log'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org2
      - FABRIC_CA_SERVER_CSR_HOSTS=rca-org2
      - FABRIC_CA_SERVER_DEBUG=true
      - BOOTSTRAP_USER_PASS=rca-org2-admin:rca-org2-adminpw
      - TARGET_CERTFILE=/data/org2-ca-cert.pem
    ports:
      - 9054:7054
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks:
      - fabric-ca

  ica-org0:
    container_name: ica-org0
    image: hyperledger/fabric-ca
    command: /bin/bash -c '/scripts/start-intermediate-ca.sh org0 2>&1 | tee /data/logs/ica-org0.log'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_CA_NAME=ica-org0
      - FABRIC_CA_SERVER_INTERMEDIATE_TLS_CERTFILES=/data/org0-ca-cert.pem
      - FABRIC_CA_SERVER_CSR_HOSTS=ica-org0
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_DEBUG=true
      - BOOTSTRAP_USER_PASS=ica-org0-admin:ica-org0-adminpw
      - PARENT_URL=https://rca-org0-admin:rca-org0-adminpw@rca-org0:7054
      - TARGET_CHAINFILE=/data/org0-ca-chain.pem
      - ORG=org0
    ports:
      - 10054:7054
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks:
      - fabric-ca
    depends_on:
      - rca-org0

  ica-org1:
    container_name: ica-org1
    image: hyperledger/fabric-ca
    command: /bin/bash -c '/scripts/start-intermediate-ca.sh org1 2>&1 | tee /data/logs/ica-org1.log'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_CA_NAME=ica-org1-admin
      - FABRIC_CA_SERVER_INTERMEDIATE_TLS_CERTFILES=/data/org1-ca-cert.pem
      - FABRIC_CA_SERVER_CSR_HOSTS=ica-org1-admin
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_DEBUG=true
      - BOOTSTRAP_USER_PASS=ica-org1-admin:ica-org1-adminpw
      - PARENT_URL=https://rca-org1-admin:rca-org1-adminpw@rca-org1:7054
      - TARGET_CHAINFILE=/data/org1-ca-chain.pem
      - ORG=org1
    ports:
      - 11054:7054
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks:
      - fabric-ca
    depends_on:
      - rca-org1

  ica-org2:
    container_name: ica-org2
    image: hyperledger/fabric-ca
    command: /bin/bash -c '/scripts/start-intermediate-ca.sh org2 2>&1 | tee /data/logs/ica-org2.log'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_CA_NAME=ica-org2
      - FABRIC_CA_SERVER_INTERMEDIATE_TLS_CERTFILES=/data/org2-ca-cert.pem
      - FABRIC_CA_SERVER_CSR_HOSTS=ica-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_DEBUG=true
      - BOOTSTRAP_USER_PASS=ica-org2-admin:ica-org2-adminpw
      - PARENT_URL=https://rca-org2-admin:rca-org2-adminpw@rca-org2:7054
      - TARGET_CHAINFILE=/data/org2-ca-chain.pem
      - ORG=org2
    ports:
      - 12054:7054
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks:
      - fabric-ca
    depends_on:
      - rca-org2

  setup:
    container_name: setup
    image: hyperledger/fabric-ca-tools
    command: /bin/bash -c '/scripts/setup-fabric.sh 2>&1 | tee /data/logs/setup.log; sleep 99999'
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks:
      - fabric-ca
    depends_on:
      - ica-org0
      - ica-org1
      - ica-org2

  run:
    container_name: run
    image: hyperledger/fabric-ca-tools
    environment:
      - GOPATH=/opt/gopath
    command: /bin/bash -c 'sleep 3;/scripts/run-fabric.sh 2>&1 | tee /data/logs/run.log; sleep 99999'
    volumes:
      - ./scripts:/scripts
      - ./data:/data
      - /Users/jeroendeprest/go/src/sandbox/fabric-samples-1.1.0-alpha/fabric-samples:/opt/gopath/src/github.com/hyperledger/fabric-samples
      - /Users/jeroendeprest/go/src/github.com/hyperledger/fabric:/opt/gopath/src/github.com/hyperledger/fabric
    networks:
      - fabric-ca
